# Generated by Django 6.0.2 on 2026-08-26 12:54

import apps.portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180, verbose_name='nome do curso')),
                ('instituicao_emissora', models.CharField(max_length=120, verbose_name='instituição emissora')),
                ('data_emissao', models.DateField(verbose_name='data de emissão')),
                ('carga_horaria', models.PositiveIntegerField(blank=True, help_text='Em horas. Deixe vazio se o certificado não informa.', null=True, verbose_name='carga horária')),
                ('link_credencial', models.URLField(blank=True, help_text='Endereço público onde a credencial pode ser conferida.', verbose_name='link de verificação')),
                ('arquivo_pdf', models.FileField(blank=True, storage=apps.portfolio.models.storage_de_arquivo, upload_to='certificados/', verbose_name='arquivo PDF')),
                ('categoria', models.CharField(choices=[('programacao', 'Programação'), ('web', 'Desenvolvimento web'), ('requisitos', 'Análise e requisitos'), ('dados', 'Dados'), ('outros', 'Outros')], default='outros', max_length=20, verbose_name='categoria')),
                ('ordem_exibicao', models.PositiveIntegerField(default=0, verbose_name='ordem de exibição')),
            ],
            options={
                'verbose_name': 'certificado',
                'verbose_name_plural': 'certificados',
                'ordering': ['ordem_exibicao', '-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('experiencia', 'Experiência profissional'), ('educacao', 'Formação acadêmica')], max_length=20, verbose_name='tipo')),
                ('cargo', models.CharField(help_text='Ex.: "Estagiário de TI — Desenvolvimento de Software" ou "Engenharia de Software".', max_length=140, verbose_name='cargo ou curso')),
                ('organizacao', models.CharField(max_length=140, verbose_name='organização')),
                ('local', models.CharField(blank=True, max_length=80, verbose_name='local')),
                ('data_inicio', models.DateField(verbose_name='início')),
                ('data_fim', models.DateField(blank=True, help_text='Deixe vazio para a entrada aparecer como "Atual".', null=True, verbose_name='término')),
                ('descricao', models.TextField(blank=True, help_text='Uma atividade por linha. Cada linha vira um item da lista.', verbose_name='descrição')),
                ('ordem_exibicao', models.PositiveIntegerField(default=0, verbose_name='ordem de exibição')),
            ],
            options={
                'verbose_name': 'experiência',
                'verbose_name_plural': 'experiências e formação',
                'ordering': ['ordem_exibicao', '-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='MensagemContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('assunto', models.CharField(blank=True, max_length=160, verbose_name='assunto')),
                ('mensagem', models.TextField(verbose_name='mensagem')),
                ('enviada_em', models.DateTimeField(auto_now_add=True, verbose_name='recebida em')),
                ('lida', models.BooleanField(default=False, verbose_name='lida')),
                ('email_enviado', models.BooleanField(default=False, help_text='Falso significa que o SMTP falhou. A mensagem está aqui de qualquer forma.', verbose_name='e-mail entregue')),
            ],
            options={
                'verbose_name': 'mensagem de contato',
                'verbose_name_plural': 'mensagens de contato',
                'ordering': ['-enviada_em'],
            },
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, help_text='Gerado a partir do nome. É o que o filtro de projetos usa no HTML — mudar depois de publicado quebra links salvos.', max_length=60, unique=True, verbose_name='identificador')),
                ('categoria', models.CharField(choices=[('backend', 'Backend'), ('database', 'Banco de dados'), ('frontend', 'Frontend'), ('engenharia', 'Engenharia e metodologias'), ('ferramentas', 'Ferramentas')], default='backend', help_text='Define em qual coluna da seção "Habilidades" a tag aparece.', max_length=20, verbose_name='categoria')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Menor primeiro, dentro da categoria.', verbose_name='ordem')),
            ],
            options={
                'verbose_name': 'tecnologia',
                'verbose_name_plural': 'tecnologias',
                'ordering': ['categoria', 'ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='identificador')),
                ('descricao_curta', models.CharField(help_text='Uma ou duas linhas. É o que aparece no cartão — o limite de 200 caracteres existe para os cartões da grade ficarem da mesma altura.', max_length=200, verbose_name='descrição curta')),
                ('descricao', models.TextField(blank=True, help_text='Opcional. Aparece ao abrir o projeto.', verbose_name='descrição completa')),
                ('imagem', models.ImageField(blank=True, help_text='Proporção 16:9 fica melhor no cartão. Sem imagem, o cartão mostra a malha técnica no lugar.', upload_to='projetos/', verbose_name='imagem')),
                ('link_github', models.URLField(blank=True, verbose_name='link do GitHub')),
                ('link_deploy', models.URLField(blank=True, verbose_name='link do site publicado')),
                ('destaque', models.BooleanField(default=False, help_text='Projetos em destaque aparecem primeiro, antes da ordem de exibição.', verbose_name='em destaque')),
                ('publicado', models.BooleanField(default=True, help_text='Desmarque para esconder do site sem apagar o cadastro.', verbose_name='publicado')),
                ('ordem_exibicao', models.PositiveIntegerField(default=0, verbose_name='ordem de exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tecnologias', models.ManyToManyField(blank=True, related_name='projetos', to='portfolio.tecnologia', verbose_name='tecnologias')),
            ],
            options={
                'verbose_name': 'projeto',
                'verbose_name_plural': 'projetos',
                'ordering': ['-destaque', 'ordem_exibicao', '-criado_em'],
            },
        ),
    ]
