# Generated by Django 6.0.2 on 2026-09-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemcontato',
            name='enviada_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='recebida em'),
        ),
    ]
