# Generated by Django 6.0.2 on 2026-09-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_mensagemcontato_enviada_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='link_video',
            field=models.URLField(blank=True, help_text='Cole a URL da página do vídeo no YouTube, do jeito que aparece na barra de endereço — funciona com o link completo, o link curto (youtu.be) ou o link de "compartilhar". Recomendado como "não listado" para não aparecer em busca nem no seu canal, só para quem tem o link. Abre num player embutido, sem sair do site.', verbose_name='link do vídeo (YouTube)'),
        ),
    ]
