# Generated by Django 6.0.2 on 2026-09-09 18:28
#
# `categoria` passa de cinco valores (backend, database, frontend,
# engenharia, ferramentas) para três (stack, ferramentas, competencias) — a
# coluna visual do quadro de habilidades vira a categoria de cadastro
# direta, sem o mapeamento à parte que existia em `GRUPO_DO_QUADRO`
# (apps/portfolio/models.py, removido nesta mudança).
#
# `choices` não é uma constraint do banco — é só validação do Django —
# então nenhuma linha existente FALHA ao gravar um valor fora da lista
# nova. Mas ficaria com um valor que a categoria não reconhece mais (o
# admin, `get_categoria_display()` etc. quebrariam a leitura), então o
# `RunPython` converte os dados ANTES do `AlterField` trocar os `choices` —
# na mesma migração, em vez de duas, porque a conversão só faz sentido
# junto com a troca de esquema que a motiva.
from django.db import migrations, models

# backend, frontend, database -> stack (a pilha que roda de fato)
# ferramentas -> ferramentas (sem mudança)
# engenharia -> competencias (paradigma/técnica/processo, não uma
# tecnologia que se instala — POO, Modelagem de dados e ETL também
# migraram para cá no semear.py, apesar de terem entrado como
# backend/database antes desta mudança)
MAPA_CATEGORIA_ANTIGA_PARA_NOVA = {
    'backend': 'stack',
    'frontend': 'stack',
    'database': 'stack',
    'ferramentas': 'ferramentas',
    'engenharia': 'competencias',
}


def migrar_categorias(apps, schema_editor):
    Tecnologia = apps.get_model('portfolio', 'Tecnologia')
    for valor_antigo, valor_novo in MAPA_CATEGORIA_ANTIGA_PARA_NOVA.items():
        if valor_antigo == valor_novo:
            continue
        Tecnologia.objects.filter(categoria=valor_antigo).update(categoria=valor_novo)


def reverter_categorias(apps, schema_editor):
    # Não há como voltar com precisão: "stack" veio de três categorias
    # diferentes (backend, frontend, database), e a informação de qual
    # delas já foi perdida no forward. Reverter para "backend" é uma
    # aproximação razoável — pelo menos volta a um valor válido no
    # esquema antigo — mas não reconstrói o dado original.
    Tecnologia = apps.get_model('portfolio', 'Tecnologia')
    Tecnologia.objects.filter(categoria='stack').update(categoria='backend')
    Tecnologia.objects.filter(categoria='competencias').update(categoria='engenharia')


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projeto_link_video'),
    ]

    operations = [
        migrations.RunPython(migrar_categorias, reverter_categorias),
        migrations.AlterField(
            model_name='tecnologia',
            name='categoria',
            field=models.CharField(choices=[('stack', 'Stack'), ('ferramentas', 'Ferramentas'), ('competencias', 'Competências')], default='stack', help_text='Define em qual coluna da seção "Habilidades" a tag aparece.', max_length=20, verbose_name='categoria'),
        ),
    ]
