# Generated by Django 6.0.2 on 2026-09-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_tecnologia_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vivencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, verbose_name='título')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='identificador')),
                ('papel', models.CharField(blank=True, help_text='O que você era ali. Ex.: "Representante de sala", "Membro".', max_length=120, verbose_name='papel')),
                ('periodo', models.CharField(blank=True, help_text='Texto livre, do jeito que faz sentido para esta atividade: "2025", "2024 — 2025", "2º semestre de 2025".', max_length=60, verbose_name='período')),
                ('descricao_curta', models.CharField(help_text='Uma ou duas linhas. É o que aparece no cartão — o limite de 200 caracteres existe para os cartões da grade ficarem da mesma altura.', max_length=200, verbose_name='descrição curta')),
                ('descricao', models.TextField(blank=True, help_text='Opcional. Aparece no botão "Detalhes" do cartão. Sem ela, o botão não é desenhado.', verbose_name='descrição completa')),
                ('imagem', models.ImageField(blank=True, help_text='Proporção 16:9 fica melhor no cartão. Sem imagem, o cartão mostra a malha técnica no lugar.', upload_to='vivencias/', verbose_name='imagem')),
                ('publicado', models.BooleanField(default=True, help_text='Desmarque para esconder do site sem apagar o cadastro.', verbose_name='publicado')),
                ('ordem_exibicao', models.PositiveIntegerField(default=0, verbose_name='ordem de exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'vivência',
                'verbose_name_plural': 'vivências',
                'ordering': ['ordem_exibicao', 'titulo'],
            },
        ),
    ]
