# Generated by Django 6.0.2 on 2026-09-10 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_vivencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivencia',
            name='imagem',
            field=models.ImageField(blank=True, help_text='A foto do cartão, e a primeira a abrir nos detalhes. Proporção 16:9 fica melhor. Sem imagem, o cartão mostra a malha técnica no lugar. As outras fotos entram logo abaixo, em "Fotos da vivência".', upload_to='vivencias/', verbose_name='imagem principal'),
        ),
        migrations.CreateModel(
            name='FotoVivencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='vivencias/', verbose_name='imagem')),
                ('legenda', models.CharField(blank=True, help_text='Opcional. Aparece abaixo da foto quando ela está aberta.', max_length=140, verbose_name='legenda')),
                ('ordem_exibicao', models.PositiveIntegerField(default=0, verbose_name='ordem de exibição')),
                ('vivencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='portfolio.vivencia', verbose_name='vivência')),
            ],
            options={
                'verbose_name': 'foto da vivência',
                'verbose_name_plural': 'fotos da vivência',
                'ordering': ['ordem_exibicao', 'pk'],
            },
        ),
    ]
