# Generated by Django 6.0.2 on 2026-09-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_vivencia_imagem_fotovivencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivencia',
            name='link_video',
            field=models.URLField(blank=True, help_text='Opcional. Cole a URL da página do vídeo no YouTube, do jeito que aparece na barra de endereço — funciona com o link completo, o link curto (youtu.be) ou o de "compartilhar". Abre num player dentro dos detalhes, sem sair do site.', verbose_name='link do vídeo (YouTube)'),
        ),
    ]
